package com.wadpam.guja.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity Di18n.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 * <p/>
 * Generated on 2014-12-07T20:44:32.554+0100.
 *
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Di18nDaoBean
    extends GeneratedDi18nDaoImpl {

  @Inject
  public Di18nDaoBean(Supplier supplier) {
    super(supplier);
  }

  public String find(String key, String baseBundle, String language) {

    // TODO

    return null;

  }

}
