package com.wadpam.guja.oauth2.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DFactory.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-12-02T22:54:58.210+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DFactoryDaoBean 
	extends GeneratedDFactoryDaoImpl
{

  @Inject
  public DFactoryDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
