package com.wadpam.guja.oauth2.dao;

import com.google.inject.Inject;

import com.wadpam.guja.exceptions.InternalServerErrorRestException;
import com.wadpam.guja.oauth2.domain.DOAuth2User;
import com.wadpam.guja.oauth2.domain.DUser;
import com.wadpam.guja.oauth2.providers.Oauth2UserProvider;
import net.sf.mardao.dao.Supplier;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;

/**
 * Implementation of Business Methods related to entity DUser.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-12-01T10:31:58.895+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DUserDaoBean extends GeneratedDUserDaoImpl {

    @Inject
    public DUserDaoBean(Supplier supplier) {
        super(supplier);
    }

}
