package com.wadpam.guja.oauth2.dao;

import com.google.inject.Inject;
import com.wadpam.guja.oauth2.domain.DUser;
import net.sf.mardao.core.CursorPage;
import net.sf.mardao.core.filter.Filter;
import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DUser.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 * <p/>
 * Generated on 2014-12-01T10:31:58.895+0100.
 *
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DUserDaoBean extends GeneratedDUserDaoImpl {

  @Inject
  public DUserDaoBean(Supplier supplier) {
    super(supplier);
  }

  public CursorPage<DUser> queryFriendsWith(Long id, int pageSize, String cursorKey) {
    return queryPage(false, pageSize, null,
        DUserMapper.Field.ID.getFieldName(), false,
        null, false,
        null, cursorKey,
        Filter.inFilter(DUserMapper.Field.FRIENDS.getFieldName(), id));
  }

}
